name: build image

on:
  push:
    branches: [example]

jobs:

  runs-on: ubuntu-latest

  steps:

    - name: checkout
      uses: actions/checkout@v5

    - name: configurar python
      uses: actions/setup-python@v5
      with:
        python-versions: '3.10'
    
    - name: instalar dependencias
      run: pip install flask
    
    - name: ejecutar las pruebas unitarias
       run: python test.py

    - name: login a Github Packages
      uses: docker//login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
      
    - name: construir y publicar imagen
      uses: docker/build-push-action@v4
      with:
        context:
        push: true
        tags: ghcr.io/${{github.repository_ower}}/python_app:latest
