name: hello world
on:
  push:
    branches: [unitest]

jobs:
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - uses: action/setup-python@v4
        with:
          python.version: '3.10'
      - run: pip install -r requirements.txt

      - run: python main_test.py